// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnocwbtogkeahqybpnrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFub2N3YnRvZ2tlYWhxeWJwbnJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxMjAzODcsImV4cCI6MjA0OTY5NjM4N30.ljNQ3-NZtd6m09wAufc_jQd9AbROLR6VYZAfJcdFW-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);